---
# tasks file for ansible-role-system_ldap
- name: "Gather OS specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_vxxxion }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"

- name: Install sssd, sssd-ldap, and sudo
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ system_ldap_packages }}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install sssd, sssd-ldap, and sudo
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ system_ldap_packages }}"
  when: ansible_distribution == 'Amazon'

- name: Copy SSSD configuration file
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: 0600
    backup: yes
    owner: root
    group: root
  notify:
    - restart sssd

- name: Query SSSD in nsswitch.conf
  replace:
    dest: /etc/nsswitch.conf
    regexp: '^({{ item }}(?!.*\bsss\b).*)$'
    replace: '\1 sss'
    backup: yes
  with_items:
    - passwd
    - shadow
    - group
    - services
    - netgroup
    - automount

- name: Don't query SSSD for sudoxxx in nsswitch.conf
  replace:
    dest: /etc/nsswitch.conf
    regexp: '^(sudoxxx.*)(\bsss)(\b.*)$'
    replace: '\1 \3'
    backup: yes

- name: Query SSSD in pam.d/password-auth
  lineinfile:
    dest: /etc/pam.d/password-auth
    insertbefore: "{{ item.before }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { before: "^auth.*pam_deny.so",
        regexp: "^auth.*pam_sss.so",
        line: "auth        sufficient    pam_sss.so use_first_pass" }
    - { before: "",
        regexp: "^account.*pam_unix.so",
        line: "account     required      pam_unix.so broken_shadow" }
    - { before: "^account.*pam_permit.so",
        regexp: "^account.*pam.sss.so",
        line: "account     [default=bad success=ok user_unknown=ignore] pam_sss.so" }
    - { before: "^password.*pam_deny.so",
        regexp: "^password.*pam_sss.so",
        line: "password    sufficient    pam_sss.so use_authtok" }
    - { before: "^session.*pam_succeed_if.so",
        regexp: "^session.*pam_.*mkhomedir.so",
        line: "session     optional      pam_oddjob_mkhomedir.so umask=0077" }
    - { before: EOF,
        regexp: "^session.*pam_sss.so",
        line: "session     optional      pam_sss.so" }
  when: ansible_os_family == 'RedHat'

- name: Query SSSD in pam.d/system-auth
  lineinfile:
    dest: /etc/pam.d/system-auth
    insertbefore: "{{ item.before }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { before: "^auth.*pam_deny.so",
        regexp: "^auth.*pam_sss.so",
        line: "auth        sufficient    pam_sss.so use_first_pass" }
    - { before: "",
        regexp: "^account.*pam_unix.so",
        line: "account     required      pam_unix.so broken_shadow" }
    - { before: "^account.*pam_permit.so",
        regexp: "^account.*pam.sss.so",
        line: "account     [default=bad success=ok user_unknown=ignore] pam_sss.so" }
    - { before: "^password.*pam_deny.so",
        regexp: "^password.*pam_sss.so",
        line: "password    sufficient    pam_sss.so use_authtok" }
    - { before: "^session.*pam_succeed_if.so",
        regexp: "^session.*pam_.*mkhomedir.so",
        line: "session     optional      pam_oddjob_mkhomedir.so umask=0077" }
    - { before: EOF,
        regexp: "^session.*pam_sss.so",
        line: "session     optional      pam_sss.so" }
  when: ansible_os_family == 'RedHat'

- name: Ensure home directories are created upon login on Debian
  lineinfile:
    dest: /etc/pam.d/common-account
    regexp: 'pam_mkhomedir\.so'
    line: "session required pam_mkhomedir.so skel=/etc/skel/ umask=0022"
    state: present
  when: ansible_os_family == 'Debian'

- name: Start and enable auth services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ system_ldap_services }}"

- name: Add LDAP groups to sudoxxx
  template:
    src: ldap_sudo_groups.j2
    dest: "/etc/sudoxxx.d/ldap_sudo_groups"
    validate: "visudo -cf %s"
    
- include: sshd.yml