---
- hosts: localhost
  connection: local
  gather_facts: true    # gather OS info that is made available for tasks/roles
  become: yes # majority of CIS tasks require root
  vars:
    ansible_python_interpreter: "/usr/bin/env python"          
  roles:
    - ldap
    - common
